# This workflow will build and publish a .NET project to a separate branch in this repo.

name: Build and Publish to separate Branch

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore project dependencies
      run: dotnet restore src/ProductCatalog.Api.csproj
      
    - name: Build the project
      run: dotnet build src/ProductCatalog.Api.csproj --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish src/ProductCatalog.Api.csproj -c Release -o .

    - name: Commit publish output to a new branch
      run: |
        git config --local user.email "ebuzycollins@gmail.com"
        git config --local user.name "ebukaracer"
        git checkout -b publish-output || git checkout publish-output
        rm -rf .github workflows src .gitattributes .gitignore .readme
        git add .
        git commit -m "Add publish files"
        git push --force origin publish-output
